setwd("D:/exdata_data_household_power_consumption")
data_all <- read.table("D:/exdata_data_household_power_consumption/household_power_consumption.txt", header = TRUE, sep = ";")
data_all$Date <- as.Date(data_all$Date, format = "%d/%m/%Y")
data = data_all[data_all$Date == "2007-02-01" | data_all$Date == "2007-02-02", ]
data$Date_Time <- paste(data$Date, " ", data$Time)
data$Date_Time <- strptime(data$Date_Time, format = "%Y-%m-%d %H:%M:%S")
data$Sub_metering_1 <- as.numeric(as.character(data$Sub_metering_1))
data$Sub_metering_2 <- as.numeric(as.character(data$Sub_metering_2))
data$Sub_metering_3 <- as.numeric(as.character(data$Sub_metering_3))
data$Global_active_power <- as.numeric(as.character(data$Global_active_power))
data$Global_reactive_power <- as.numeric(as.character(data$Global_reactive_power))
data$Voltage <- as.numeric(as.character(data$Voltage))

png(file = "plot4.png", width=480, height=480)
par(mfrow=c(2,2))
plot(data$Date_Time, data$Global_active_power, type="l", ylab = "Global Active Power (kilowatts)", xlab = "")
plot(data$Date_Time, data$Voltage, type="l", ylab = "Voltage", xlab = "datetime")
plot(data$Date_Time, data$Sub_metering_1, type = "l", ylab = "Energy sub metering", xlab = "")
lines(data$Date_Time, data$Sub_metering_2, col = "red")
lines(data$Date_Time, data$Sub_metering_3, col = "blue")
legend("topright", col = c("black","red","blue"), c("Sub_metering_1","Sub_metering_2", "Sub_metering_3"), lty=c(1,1), lwd=c(1,1), bty="n")
plot(data$Date_Time, data$Global_reactive_power, type="l", ylab = "Global_reactive_power", xlab = "datetime")
dev.off()